export type ColorType = "primary" | "secondary" | "gray" | "danger" | "warning" | "info" | "light" | "dark"
export type OutlineType =
  | "outline-primary"
  | "outline-secondary"
  | "outline-gray"
  | "outline-danger"
  | "outline-warning"
  | "outline-info"
  | "outline-light"
  | "outline-dark"
export type FontType = "sans" | "heading" | "outfit" | "carterOne"
export type RoundedType = "none" | "sm" | "base" | "md" | "lg" | "xl" | "2xl" | "3xl" | "full"
