export type ColorType =
  | "primary"
  | "secondary"
  | "gray"
  | "danger"
  | "warning"
  | "info"
  | "light"
  | "dark"
  | "black"
  | "white"
export type OutlineType =
  | "outline-primary"
  | "outline-secondary"
  | "outline-gray"
  | "outline-danger"
  | "outline-warning"
  | "outline-info"
  | "outline-light"
  | "outline-dark"
  | "outline-black"
  | "outline-white"
export type FontType = "sans" | "heading" | "outfit" | "carterOne"
export type RoundedType = "none" | "sm" | "base" | "md" | "lg" | "xl" | "2xl" | "3xl" | "full"
