#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

(yarn lint:js && yarn lint:prettier) ||
(
    echo "🔨❌ You have a problem in your code. Check linter 🔨❌
          Run yarn lint or yarn lintfix, add changes and try commit again.";
    false;
)
